name: Publish to PyPI

on:
  push:
    branches: ["master"]

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: "actions/checkout@v2"
      - uses: "actions/setup-python@v2"
        with:
          python-version: "3.10"
          architecture: x64
      - name: my-step
        run: echo "Hello World!"
      - name: "Install"
        run: |
          python -VV
          python -m pip install -U pip setuptools wheel twine luddite
          python -m pip wheel --no-deps .
          ls -l .
