name: tests

on:
  pull_request:
    branches: ["main"]
  workflow_dispatch:

jobs:
  tests:
    name: "Python ${{ matrix.python-version }} on ${{ matrix.os }}"
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        python-version: ["3.11"]

    steps:
      - uses: "actions/checkout@v3"
      - uses: "actions/setup-python@v4"
        with:
          python-version: "${{ matrix.python-version }}"
          architecture: x64
          cache: "pip"
      - name: "Install"
        run: |
          python -VV
          python -m pip install -U pip setuptools wheel
          python -m pip install pytest>=7rc1 pytest-socket --editable .
          python -m pip freeze --all
      - name: "Run tests for ${{ matrix.python-version }} on ${{ matrix.os }}"
        run: python -m pytest -v --durations=10 --disable-socket
